print("                   " + "Toko Mainan Anak" + "                   ")
print("                " + "**********************" + "                ")
Nama = input("Masukan Nama Pembeli : ")
KodeMainan = input("Masukan Kode Mainan : ")
Harga = int(input("Masukan Harga : "))
JumlahBeli = int(input("Masukan Jumlah Beli : "))
print("============================================")
print("Nama Pembeli = " + Nama)
print("Kode Mainan  = " + KodeMainan)
print("Harga        = ", Harga)
print("Jumlah Beli  = ", JumlahBeli)
print("Total        = ", Harga * JumlahBeli)